// Generated by CoffeeScript 1.6.3
(function() {
  var Fretboard, main;

  console.log("foobar!");

  Fretboard = (function() {
    function Fretboard(strings) {
      this.strings = strings;
    }

    return Fretboard;

  })();

  main = function() {
    var fb, strings;
    strings = [7, 0, 4, 9];
    fb = Fretboard(strings);
    return console.log(fb);
  };

  window.onload = main;

}).call(this);
